version: '3.8'

services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/TANK/docker/syncthing/config:/config
      - /mnt/TANK/docker/syncthing/sync:/sync
    ports:
      - "8384:8384"     # Web UI
      - "22000:22000/tcp" # TCP file transfers
      - "22000:22000/udp" # QUIC file transfers
      - "21027:21027/udp" # Receive local discovery broadcasts
    restart: unless-stopped
    networks:
      - syncthing-network

networks:
  syncthing-network:
    driver: bridge